// <auto-generated />
using System;
using Devices.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devices.API.Migrations
{
    [DbContext(typeof(DevicesDbContext))]
    [Migration("20230420200929_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devices.API.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("advancedEnvironmentalConditions")
                        .HasColumnType("bit");

                    b.Property<string>("deviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deviceTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("failsafe")
                        .HasColumnType("bit");

                    b.Property<bool>("insertIntol9InchCabinet")
                        .HasColumnType("bit");

                    b.Property<string>("installationPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("motionEnable")
                        .HasColumnType("bit");

                    b.Property<double>("positionAxisNumber")
                        .HasColumnType("float");

                    b.Property<double>("rotationAxisNumber")
                        .HasColumnType("float");

                    b.Property<bool>("simaticCatalog")
                        .HasColumnType("bit");

                    b.Property<bool>("siplusCatalog")
                        .HasColumnType("bit");

                    b.Property<double>("tempMax")
                        .HasColumnType("float");

                    b.Property<double>("tempMin")
                        .HasColumnType("float");

                    b.Property<bool?>("terminalEvent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
